services:
  designcreate_dev:
    container_name: designcreate_dev
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ../backend:/usr/app/backend
      - ../share:/usr/app/share
      - /usr/app/backend/node_modules
      
  designcreate:
    container_name: designcreate
    environment:
      - HOST=mongo
    build:
      dockerfile: pro.Dockerfile

  mongo:
    image: mongo:5.0.14
    container_name: mongo_dev
    ports:
      - 27018:27017
    restart: always
    
networks:
  default:
    name: docker-network
    external: true