services:
  backend:
    container_name: designcreate_backend
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ../backend:/usr/app/backend
      - ../share:/usr/app/share
      - /usr/app/backend/node_modules
  backend_pro:
    container_name: designcreate_backend
    environment:
      - HOST=mongo_pro
    build:
      dockerfile: pro.Dockerfile
  mongo:
    image: mongo:5.0.14
    container_name: mongo_dev
    ports:
      - 27018:27017
    restart: always
    
networks:
  default:
    name: development
    external: true