name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build and Deploy
      run: 
        docker compose up backend_pro --build -d
