name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    environment: dev
    steps: 
    - name: Delete all the resources
      run: echo ${{secrets.SUDO_PASSWORD}} | sudo -S rm -r ../DesignCreate
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: 
        echo ${{secrets.SUDO_PASSWORD}} | sudo -S bash ./docker-pro.sh ${{secrets.API}} ${{secrets.DBUSER}} ${{secrets.DBPASSWORD}} 
