name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: copy share folder inside frontend
      run: 
        cp ./shape ./frontend
    - name: Build the Docker image
      run: 
        echo ${{secrets.SUDO_PASSWORD}} | sudo -S bash ./docker-pro.sh ${{secrets.API}} ${{secrets.DBUSER}} ${{secrets.DBPASSWORD}} 
