name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        run: echo ${{secrets.SSH_PRIVATE_KEY}} | sudo -S docker compose -f ./backend/docker-compose.yml up --build -d designcreate_pro
