name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          echo "${{ secrets.PACKAGE_TOKEN }}" | docker login -u gabrielopensource --password-stdin ghcr.io
          docker compose -f ./backend/docker-compose.yml build designcreate_pro
          docker push ghcr.io/gabrieltrinidad0101/backend-designcreate_pro:latest
  deploy:
    needs: [build-image]
    runs-on: self-hosted
    steps:
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ghcr.io -u gabrielopensource --password-stdin

      - name: Update Container
        run: |
          echo ${{secrets.SSH_PRIVATE_KEY}} | sudo -S docker stop designcreate_pro || true
          echo ${{secrets.SSH_PRIVATE_KEY}} | sudo -S docker rm designcreate_pro || true
          echo ${{secrets.SSH_PRIVATE_KEY}} | sudo -S docker pull ghcr.io/gabrieltrinidad0101/backend-designcreate_pro:latest
          echo ${{secrets.SSH_PRIVATE_KEY}} | sudo -S docker run -d --name designcreate_pro --network docker-network -e HOST=mongo ghcr.io/gabrieltrinidad0101/backend-designcreate_pro:latest