name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: gabrielopensource
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build
        run: |
          docker build -t designcreate_pro --build-arg HOST=mongo -f backend/pro.Dockerfile backend
          docker push ghcr.io/gabrieltrinidad0101/backend-designcreate_pro:latest
