name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gabrielopensource
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: backend/pro.Dockerfile
          build-args: |
            HOST=mongo
          push: true
          tags: |
            ghcr.io/gabrielopensource/backend-designcreate_pro:latest
            ghcr.io/gabrielopensource/backend-designcreate_pro:${{ github.sha }}