services:
  backend:
    container_name: backend_container
    build: ../backend
    ports:
      - 4000:4000
    volumes:
      - ../backend:/usr/app/backend
      - ../share:/usr/app/backend
      - /usr/app/backend/node_modules
    networks:
      - redDatabase
      - redBackend